name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ZOOM_API_KEY: ${{ secrets.ZOOM_API_KEY }}
  ZOOM_API_SECRET: ${{ secrets.ZOOM_API_SECRET }}
  ZOOM_EXAMPLE_EMAIL: ${{ secrets.ZOOM_EXAMPLE_EMAIL }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Test
      run: go test -v ./...